#!/bin/bash

automated_update_msg () {
    echo "AUTOMATED DOTFILES UPDATE | $(whoami)@$(hostname) (ﾟヮﾟ)"
}

sync_submodules () {
    VIMDIR=".vim/bundle"
    SUBMODULES=".emacs.d ${VIMDIR}/ctrlp-matcher ${VIMDIR}/vim-fugitive ${VIMDIR}/vim-go"
    for submodule in ${SUBMODULES}; do
        echo "Updating ${submodule}..."
        cd ${submodule} >/dev/null
        git add --all >/dev/null && git commit -m "$(automated_update_msg)"
        cd - >/dev/null
    done
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
case "$1" in
    diff)
        cd ${DIR} >/dev/null
        git diff
        cd - >/dev/null
        ;;
    install)
        rm -rf ${HOME}/.vim ${HOME}/.vimrc ${HOME}/.bashrc ~/.emacs.d
        cd ${DIR} >/dev/null
        git submodule update --init --recursive
        cd - >/dev/null
        ln -s ${DIR}/.vim ${HOME}/.vim
        ln -s ${DIR}/.vimrc ${HOME}/.vimrc
        ln -s ${DIR}/.bashrc ${HOME}/.bashrc
        ln -s ${DIR}/.emacs.d ${HOME}/.emacs.d
        . ${HOME}/.bashrc
        ;;
    provision)
        if [[ "$2" == "ubuntu" ]]; then
            sudo apt-get install -y tree mercurial
        fi
        ;;
    sync)
        cd ${DIR} >/dev/null
        git fetch origin
        if [[ "$2" == "" ]]; then
            MSG=$(automated_update_msg)
        else
            MSG=$2
        fi
        sync_submodules
        git add --all . && \
            git commit -m "${MSG}"
        git rebase origin/master
        git push origin master
        cd - >/dev/null
        ;;
    *)
        echo "Usage: dotfiles [diff|install|sync]"
        exit 1
esac
