#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
case "$1" in 
    diff)
        cd ${DIR} >/dev/null
        git diff 
        cd - >/dev/null
        ;;
    install)
        rm -rf ${HOME}/.vim ${HOME}/.vimrc ${HOME}/.bashrc ~/.emacs.d
        git submodule update --init --recursive
        ln -s ${DIR}/.vim ${HOME}/.vim
        ln -s ${DIR}/.vimrc ${HOME}/.vimrc
        ln -s ${DIR}/.bashrc ${HOME}/.bashrc
        ln -s ${DIR}/.emacs.d ${HOME}/.emacs.d
        . ${HOME}/.bashrc
        ;;
    sync)
        cd ${DIR} >/dev/null
        git fetch origin
        if [[ "$2" == "" ]]; then
            MSG="AUTOMATED DOTFILES UPDATE | $(whoami)@$(hostname) (ﾟヮﾟ)"
        else
            MSG=$2
        fi
        git add --all . && \
            git commit -m "${MSG}"
        git rebase origin/master
        git push origin master
        cd - >/dev/null
        ;;
    *)
        echo "Usage: dotfiles [diff|install|sync]"
        exit 1
esac
